# Goal
float64[] target_joints # put 6 joints
int32 task_type         # 0:move, 1:grip, 2:release
---
# Result
bool success            # (True/False)
string message          # Finished
---
# Feeedback
string status       
